<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.11.0(352)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateNasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('nas')) {
            Schema::create('nas', function (Blueprint $table) {
                $table->integer('id')->autoIncrement();
                $table->string('nasname', 128);
                $table->string('shortname', 32)->nullable()->default(null);
                $table->string('type', 30)->nullable()->default('other');
                $table->integer('ports')->nullable()->default(null);
                $table->string('secret', 60)->default('secret');
                $table->string('server', 64)->nullable()->default(null);
                $table->string('community', 50)->nullable()->default(null);
                $table->string('description', 200)->nullable()->default('RADIUS Client');
            });
        }

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('nas');
    }

    public function getConnection()
    {
        return config('radius.database.connection');
    }
}
