<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.11.0(352)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateRadacctTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('radacct', function (Blueprint $table) {
            $table->bigInteger('radacctid')->autoIncrement();
            $table->string('acctsessionid', 64)->default('');
            $table->string('acctuniqueid', 32)->default('');
            $table->string('username', 64)->default('');
            $table->string('realm', 64)->nullable()->default('');
            $table->string('nasipaddress', 15)->default('');
            $table->string('nasportid', 15)->nullable()->default(NULL);
            $table->string('nasporttype', 32)->nullable()->default(NULL);
            $table->datetime('acctstarttime')->nullable()->default(NULL);
            $table->datetime('acctupdatetime')->nullable()->default(NULL);
            $table->datetime('acctstoptime')->nullable()->default(NULL);
            $table->integer('acctinterval')->nullable()->default(NULL);
            $table->integer('acctsessiontime')->unsigned()->nullable()->default(NULL);
            $table->string('acctauthentic', 32)->nullable()->default(NULL);
            $table->string('connectinfo_start', 50)->nullable()->default(NULL);
            $table->string('connectinfo_stop', 50)->nullable()->default(NULL);
            $table->bigInteger('acctinputoctets')->nullable()->default(NULL);
            $table->bigInteger('acctoutputoctets')->nullable()->default(NULL);
            $table->string('calledstationid', 50)->default('');
            $table->string('callingstationid', 50)->default('');
            $table->string('acctterminatecause', 32)->default('');
            $table->string('servicetype', 32)->nullable()->default(NULL);
            $table->string('framedprotocol', 32)->nullable()->default(NULL);
            $table->string('framedipaddress', 15)->default('');
            $table->string('framedipv6address', 45)->default('');
            $table->string('framedipv6prefix', 45)->default('');
            $table->string('framedinterfaceid', 44)->default('');
            $table->string('delegatedipv6prefix', 45)->default('');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('radacct');
    }

    public function getConnection()
    {
        return config('radius.database.connection');
    }
}
